const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let data={};let session=JSON.parse(localStorage.getItem('resqsimSession')||'null');
async function api(url,opt={}){const r=await fetch('/api'+url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.message||'Request failed');return body}
function toast(m){const x=$('#toast');x.textContent=m;x.style.display='block';setTimeout(()=>x.style.display='none',2800)}
function openModal(id){$('#'+id).classList.add('show')} function closeModal(id){$('#'+id).classList.remove('show')}
$$('.login-tab').forEach(b=>b.onclick=()=>{ $$('.login-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const admin=b.dataset.role==='admin';$('#adminLogin').classList.toggle('hidden',!admin);$('#victimLogin').classList.toggle('hidden',admin);});
$('#adminLogin').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await doLogin({role:'admin',email:f.get('email'),password:f.get('password')})};
$('#victimLogin').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await doLogin({role:'victim',victimId:Number(f.get('victimId')),phone:f.get('phone')})};
async function doLogin(payload){try{const r=await api('/login',{method:'POST',body:JSON.stringify(payload)});session=r;localStorage.setItem('resqsimSession',JSON.stringify(r));showApp();toast('Signed in successfully')}catch(e){toast(e.message)}}
function showApp(){if(!session)return;$('#loginScreen').classList.add('hidden');if(session.role==='admin'){ $('#adminApp').classList.remove('hidden');$('#victimApp').classList.add('hidden');loadAll()}else{$('#victimApp').classList.remove('hidden');$('#adminApp').classList.add('hidden');loadVictimPortal()}}
function logout(){session=null;localStorage.removeItem('resqsimSession');$('#adminApp').classList.add('hidden');$('#victimApp').classList.add('hidden');$('#loginScreen').classList.remove('hidden')}
const labels={dashboard:['Operations Dashboard','Live disaster response overview'],victims:['Victim Management','Registered people and current response status'],sos:['Emergency / SOS Queue','Prioritize and dispatch help'],teams:['Rescue Teams','Dispatch teams to active emergencies'],volunteers:['Volunteers','People and skills supporting response'],shelters:['Shelters','Emergency accommodation capacity'],resources:['Resources','Supply requests and allocation'],scheduling:['OS Scheduling Lab','FCFS and Priority scheduling'],reports:['Response Report','Operational summary']};
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+page).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=labels[page][0];$('#pageSub').textContent=labels[page][1];if(page==='reports')loadReport()}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));
async function loadAll(){try{const [dash,victims,sos,teams,vols,shelters,res]=await Promise.all([api('/dashboard'),api('/victims'),api('/admin/sos'),api('/teams'),api('/volunteers'),api('/shelters'),api('/admin/resources')]);data={victims,teams,sos,vols,shelters,res};renderDash(dash);renderVictims(victims);renderSos(sos);renderTeams(teams);renderVols(vols);renderShelters(shelters);renderResources(res);fillSelects(shelters,teams);const h=await api('/health');$('#dbState').textContent=h.ok?'● MySQL connected':'● Database error';$('#dbState').className='db-pill '+(h.ok?'ok':'bad')}catch(e){$('#dbState').textContent='● Database offline';$('#dbState').className='db-pill bad';toast('Could not load data: '+e.message)}}
function renderDash(d){$('#heroSos').textContent=d.pendingSos;$('#stats').innerHTML=[['Victims',d.victims,'👥'],['Pending SOS',d.pendingSos,'🚨'],['Assigned teams',d.activeTeams,'🚑'],['Available beds',d.availableBeds,'🏠']].map(x=>`<div class="stat"><span>${x[2]}</span><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('#dashSos').innerHTML=(data.sos||[]).slice(0,5).map(x=>`<div class="alert-row"><div><b>${x.name}</b><small>${x.location||'Location pending'} · ${x.emergency_type||'Emergency'}</small></div><span class="badge red">Severity ${x.severity}</span></div>`).join('')||'<p class="muted">No pending SOS requests.</p>';let total=d.availableTeams+d.activeTeams||1;$('#capacity').innerHTML=`<div class="metric"><div><span>Teams available</span><b>${d.availableTeams}</b></div><div class="mini-progress"><span style="width:${d.availableTeams/total*100}%"></span></div></div><div class="metric"><div><span>Volunteers registered</span><b>${d.volunteers}</b></div></div>`}
const badge=s=>`<span class="badge ${s?.includes('Pending')||s?.includes('Severity 5')?'red':s?.includes('Allocated')||s==='Approved'||s==='Available'?'green':'blue'}">${s||'—'}</span>`;
function renderVictims(a){$('#victimRows').innerHTML=a.map(x=>`<tr><td>#${x.victim_id}</td><td><b>${x.name}</b></td><td>${x.phone||'—'}</td><td>${x.location||'—'}</td><td>${x.emergency_type||'—'}</td><td>${x.severity||'—'}</td><td>${badge(x.status)}</td><td><button class="ghost small" onclick="openSos(${x.victim_id})">SOS</button> <button class="ghost small" onclick="requestResource(${x.victim_id})">Resource</button></td></tr>`).join('')||'<tr><td colspan="8">No victims yet.</td></tr>'}
function renderSos(a){$('#sosRows').innerHTML=a.map(x=>`<tr><td>#${x.victim_id}</td><td><b>${x.name}</b><small>${x.phone||''}</small></td><td>${x.location||'—'}</td><td>${x.emergency_type||'—'}</td><td>${badge('Severity '+x.severity)}</td><td>${x.team_id?badge('Assigned'):badge('Pending')}</td><td><button class="ghost small" onclick="openTeam(${x.victim_id})">Assign team</button></td></tr>`).join('')||'<tr><td colspan="7">No pending SOS requests.</td></tr>'}
function renderTeams(a){$('#teamCards').innerHTML=a.map(x=>`<div class="card team"><div class="team-icon">🚑</div><h3>${x.team_name}</h3><p>${x.leader||'—'} · ${x.vehicle||'—'}</p>${badge(x.rescue_status)}${x.victim_id?`<p class="muted">Assigned to victim #${x.victim_id}</p>`:''}</div>`).join('')}
function renderVols(a){$('#volRows').innerHTML=a.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.phone||'—'}</td><td>${x.skill||'—'}</td><td>${x.shelter_name||'—'}</td><td>${badge(x.availability)}</td><td><button class="ghost small" onclick="toggleVol(${x.volunteer_id},'${x.availability==='Available'?'Unavailable':'Available'}')">Toggle</button></td></tr>`).join('')||'<tr><td colspan="6">No volunteers yet.</td></tr>'}
function renderShelters(a){$('#shelterCards').innerHTML=a.map(x=>`<div class="card shelter"><div class="shelter-top"><div class="shelter-icon">🏠</div>${badge(x.available_beds>0?'Available':'Full')}</div><h3>${x.shelter_name}</h3><p>${x.address}</p><div class="bed-number"><b>${x.available_beds}</b><span>available beds of ${x.capacity}</span></div><div class="progress"><span style="width:${Math.min(100,x.available_beds/x.capacity*100)}%"></span></div><button class="ghost" onclick="assignShelter(${x.shelter_id})">Assign to victim</button></div>`).join('')||'<div class="card"><p>No shelters available.</p></div>'}
function renderResources(a){$('#resourceRows').innerHTML=a.map(x=>`<tr><td>#${x.victim_id} <b>${x.name}</b></td><td>${x.resource_request}</td><td>${badge(x.resource_status)}</td><td><button class="ghost small" onclick="allocate(${x.victim_id})">Allocate</button></td></tr>`).join('')||'<tr><td colspan="4">No pending resource requests.</td></tr>'}
function fillSelects(shelters,teams){$('#teamSelect').innerHTML=teams.filter(x=>x.rescue_status==='Available').map(x=>`<option value="${x.team_id}">${x.team_name} — ${x.vehicle||''}</option>`).join('');$('#volShelter').innerHTML='<option value="0">No shelter</option>'+shelters.map(x=>`<option value="${x.shelter_id}">${x.shelter_name}</option>`).join('')}
async function registerVictim(e){e.preventDefault();try{const f=new FormData(e.target);const r=await api('/victims',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});closeModal('victimModal');e.target.reset();toast(r.message+` — Victim ID ${r.victimId}`);loadAll()}catch(x){toast(x.message)}}
function openSos(id){$('#sosModal input[name=id]').value=id;openModal('sosModal')} async function createSos(e){e.preventDefault();try{const f=new FormData(e.target),id=f.get('id');await api(`/victims/${id}/sos`,{method:'PUT',body:JSON.stringify(Object.fromEntries(f))});closeModal('sosModal');toast('SOS created successfully');loadAll()}catch(x){toast(x.message)}}
function openTeam(id){$('#teamModal input[name=victimId]').value=id;openModal('teamModal')} async function assignTeam(e){e.preventDefault();try{const f=new FormData(e.target);await api('/admin/assign-team',{method:'PUT',body:JSON.stringify(Object.fromEntries(f))});closeModal('teamModal');toast('Rescue team assigned');loadAll()}catch(x){toast(x.message)}}
async function requestResource(id){const resource=prompt('Enter resource needed:');if(!resource)return;try{await api(`/victims/${id}/resource`,{method:'PUT',body:JSON.stringify({resource})});toast('Resource request sent');loadAll()}catch(x){toast(x.message)}} async function allocate(id){await api('/admin/resources/'+id,{method:'PUT'});toast('Resources allocated');loadAll()}
async function addVolunteer(e){e.preventDefault();try{const f=new FormData(e.target),o=Object.fromEntries(f);o.shelterId=Number(o.shelterId)||null;await api('/volunteers',{method:'POST',body:JSON.stringify(o)});closeModal('volunteerModal');e.target.reset();toast('Volunteer added');loadAll()}catch(x){toast(x.message)}}
async function toggleVol(id,a){await api(`/volunteers/${id}/availability`,{method:'PUT',body:JSON.stringify({availability:a})});loadAll()}
async function assignShelter(id){const victim=prompt('Enter Victim ID to assign this shelter:');if(!victim)return;try{await api('/admin/shelter',{method:'PUT',body:JSON.stringify({victimId:Number(victim),shelterId:id})});toast('Shelter assigned');loadAll()}catch(x){toast(x.message)}}
async function loadReport(){try{const a=await api('/report');$('#reportRows').innerHTML=a.map(x=>`<tr><td>#${x.victim_id} ${x.name}</td><td>${x.location||'—'}</td><td>${x.emergency_type||'—'}</td><td>${x.severity||'—'}</td><td>${badge(x.status)}</td><td>${x.team_name||'—'}</td><td>${x.shelter_name||'—'}</td><td>${x.resource_status||'—'}</td></tr>`).join('')}catch(e){toast(e.message)}}
async function runSchedule(type){try{const raw=$('#'+(type==='fcfs'?'fcfsInput':'priorityInput')).value.trim().split('\n').filter(Boolean);let jobs=raw.map(line=>{const p=line.split(',').map(x=>x.trim());return type==='fcfs'?{id:p[0],arrival:Number(p[1]),burst:Number(p[2])}:{id:p[0],burst:Number(p[1]),priority:Number(p[2])}});const r=await api('/scheduling/'+type,{method:'POST',body:JSON.stringify(jobs)});$('#scheduleResult').innerHTML=`<h3>Scheduling result</h3><div class="schedule-metrics"><span>Average waiting <b>${r.avgWaiting.toFixed(2)}</b></span><span>Average turnaround <b>${r.avgTurnaround.toFixed(2)}</b></span></div><div class="tablewrap"><table><thead><tr>${Object.keys(r.jobs[0]||{}).map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${r.jobs.map(j=>`<tr>${Object.values(j).map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}catch(e){toast(e.message)}}
async function loadVictimPortal(){try{const id=session.user.victim_id;const [v,shelters]=await Promise.all([api('/victim/'+id+'/full'),api('/shelters')]);session.user=v;localStorage.setItem('resqsimSession',JSON.stringify(session));$('#vName').textContent='Hello, '+v.name;$('#vStatus').textContent=v.status||'Registered';$('#victimStatusCard').innerHTML=`<div class="status-list"><div><span>Emergency</span><b>${v.emergency_type||'No SOS yet'}</b></div><div><span>Severity</span><b>${v.severity||'—'}</b></div><div><span>Rescue team</span><b>${v.team_name||'Not assigned'}</b></div><div><span>Shelter</span><b>${v.shelter_name||'Not assigned'}</b></div><div><span>Resources</span><b>${v.resource_status||'No request'}</b></div></div>`;$('#victimShelters').innerHTML=shelters.slice(0,4).map(s=>`<div class="shelter-mini"><b>${s.shelter_name}</b><span>${s.available_beds} beds available</span></div>`).join('')||'<p class="muted">No shelter currently has capacity.</p>'}catch(e){toast(e.message)}}
$('#resourceForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await api(`/victims/${session.user.victim_id}/resource`,{method:'PUT',body:JSON.stringify({resource:f.get('resource')})});e.target.reset();toast('Resource request submitted');loadVictimPortal()}catch(x){toast(x.message)}};
async function victimSendSos(e){e.preventDefault();try{const f=new FormData(e.target);await api(`/victims/${session.user.victim_id}/sos`,{method:'PUT',body:JSON.stringify(Object.fromEntries(f))});closeModal('victimSosModal');toast('Emergency SOS sent to command center');loadVictimPortal()}catch(x){toast(x.message)}}
if(session)showApp();
